trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - bash: |
        # Generate a random port number between 3000 and 6000
        export RANDOM_PORT=$((RANDOM % (6000-3000+1) + 3000))

        # Print the random port for reference
        echo "Random Port: $RANDOM_PORT"

        # Store the random port in an environment variable for later use
        echo "##vso[task.setvariable variable=portNumber;isOutput=true]$RANDOM_PORT"
      displayName: 'GENERATE RANDOM PORT'
      name: DockerPort
- stage: B
  dependsOn: A
  jobs:
  - job: B1
    variables:
      dockerPortNumber: $[stageDependencies.A.A1.outputs['DockerPort.portNumber']]
    steps:
    - bash: echo '$(dockerPortNumber)'
- stage: C
  dependsOn:
  - A
  - B
  jobs:
  - job: C1
    variables:
      dockerPortNumber: $[stageDependencies.A.A1.outputs['DockerPort.portNumber']]
    steps:
      - bash: echo '$(dockerPortNumber)'
      - bash: echo 'JobStatus >>>>> $(stageDependencies.A.A1.JobStatus)'
      - bash: echo '$(Build.RequestedForEmail)'
      - bash: echo $(Agent.JobStatus)

