trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    # Generate a random port number between 3000 and 6000
    export RANDOM_PORT=$((RANDOM % (6000-3000+1) + 3000))

    # Print the random port for reference
    echo "Random Port: $RANDOM_PORT"

    # Store the random port in an environment variable for later use
    echo "##vso[task.setvariable variable=DOCKER_PORT]$RANDOM_PORT"
  displayName: 'GENERATE RANDOM PORT'

- bash: echo $(DOCKER_PORT) 
