trigger: none
pr: none
resources:
  pipelines:
  - pipeline: TestWeeklyBuild
    source: test-weekly-build
    trigger:
      stages:
      - CreateReleaseVersion

pool:
  vmImage: ubuntu-latest

steps:
- ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
  - script: |
      echo Triggered from test-weekly-build!
    displayName: 'Run a one-line script'

- script: |
    echo Build reason ::: $(Build.Reason)
  displayName: 'Run a multi-line script'
  condition: ne(variables['Build.Reason'], 'ResourceTrigger')
