trigger: none
schedules:
- cron: '1 0 * * 6' # Every Saturday 00.01 AM
  displayName: 'Weekly midnight build'
  branches:
    include:
    - develop

variables:
  - name: Year
    value: $[format('{0:yyyy}', pipeline.startTime)]
  - name: Month
    value: $[format('{0:M}', pipeline.startTime)]
  - name: Patch
    value: $[counter(format('{0}.{1}', variables['Year'], variables['Month']), 1)]
  - name: weeklyBranchName
    value: 'weekly/$(Year).$(Month).$(Patch)'
  - name: PipelineStartDate
    value: $[format('{0:dd}/{0:MM}/{0:yyyy} {0:HH}:{0:mm}:{0:ss}', pipeline.startTime)]

pool: 
  vmImage: 'ubuntu-latest'

stages:
## 
  - stage: CreateChromeBranchAndPR
    displayName: '[CHROME] CHECKOUT AND CREATE WEEKLY BRANCH PR'
    dependsOn: []
    jobs: 
    - job: CreateChromeBranchAndPRJob
      steps:
      - checkout: self
        lfs: true
        persistCredentials: true
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo "Branch name: $(weeklyBranchName)"
            git config --global user.email "devops@ironsoftware.com"
            git config --global user.name "DevOps"
            git checkout -b $(weeklyBranchName)
            git push -u origin $(weeklyBranchName)
            
            if [[ $(git diff --name-only master..$(weeklyBranchName)) ]]; then
              gh pr create --title "[Automation] Weekly Build $(PipelineStartDate)" --body "This PR includes the weekly build base on \`$(Build.SourceBranchName)\` branch on $(Build.SourceVersion) commit.\nPlease review the IronPdf SmokeTests and merge this PR when ready." --base $(Build.SourceBranchName)
            else
              echo "No changes detected. Skipping pull request creation."
            fi
        env:
          GH_TOKEN: $(GitHub_PAT)
        displayName: 'CREATE BRANCH & PULL REQUEST'